import { Inter } from 'next/font/google'
import Head from 'next/head'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const inter = Inter({ 
  subsets: ['latin'],
  weight: '200',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className}>
       <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Your Site Title</title>
      </Head>
      <body>
        <div className='header-div'>
          {children}
        </div>
      </body>
    </html>
  )
}